repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.6.0
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
    -   repo: https://github.com/pre-commit/mirrors-yapf
        rev: v0.32.0
        hooks:
            - id: yapf
              additional_dependencies:
                  - toml
    -   repo: https://github.com/pycqa/flake8
        rev: 6.1.0
        hooks:
            - id: flake8
              additional_dependencies:
                  - flake8-bugbear
                  - flake8-builtins
                  - flake8-coding
                  - flake8-import-order
                  - flake8-polyfill
                  - flake8-quotes
